-- ============================================================
-- BYPASS SHOP — Staff Feed (group chat)
-- Run once in: Supabase Dashboard → SQL Editor → New query → Run.
-- Safe to re-run.
--
-- A single shop-wide group chat. Every signed-in staff member can post
-- and read messages (enquiries, best-price questions, general info).
-- Each message shows the sender's name and time.
-- ============================================================

create table if not exists public.messages (
  id         bigint generated by default as identity primary key,
  user_id    uuid references auth.users (id) on delete set null,
  author     text not null,          -- display name, denormalised so it survives account deletion
  body       text not null,
  created_at timestamptz not null default now()
);

create index if not exists messages_created_at_idx on public.messages (created_at);

-- Lock it down: only signed-in staff can read/post.
alter table public.messages enable row level security;

drop policy if exists "messages_read" on public.messages;
create policy "messages_read" on public.messages
  for select to authenticated using (true);

-- Anyone signed in can post, but only as themselves.
drop policy if exists "messages_insert" on public.messages;
create policy "messages_insert" on public.messages
  for insert to authenticated with check (auth.uid() = user_id);

-- A sender can delete their own message; admins can delete any.
drop policy if exists "messages_delete" on public.messages;
create policy "messages_delete" on public.messages
  for delete to authenticated using (
    auth.uid() = user_id
    or (select lower(email) from auth.users where id = auth.uid())
         in ('admin@bypassshop.co', 'addamsjmk@gmail.com')
  );

-- Broadcast new messages to everyone in realtime (live chat).
do $$
begin
  begin execute 'alter publication supabase_realtime add table public.messages'; exception when others then null; end;
end $$;
