-- BYPASS SHOP — real stock import (editable rows, not hardcoded)
-- Generated from the shop list dated 20 July 2026.
insert into public.inventory
  (code, cat, brand, model, year_from, year_to, condition, side, name, price, qty, min_qty, location, notes, status, created_by)
values
  ('WNR-TOY-WIS-10-R-0001', 'WNR', 'Toyota', 'Wish', 2010, 2010, 'Genuine Used', 'Right', 'Toyota Wish 2010 Right Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNR-TOY-WIS-10-R-0002', 'WNR', 'Toyota', 'Wish', 2010, 2010, 'Genuine Used', 'Right', 'Toyota Wish 2010 Right Wing with Indicator', 0, 1, 1, 'Unassigned', 'Wing with Indicator', 'Active', 'Josphat Kamau'),
  ('WNR-TOY-VOX-10-R-0003', 'WNR', 'Toyota', 'Voxy', 2010, 2010, 'Genuine Used', 'Right', 'Toyota Voxy 2010 Right Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNR-HON-FIT-10-R-0004', 'WNR', 'Honda', 'Fit', 2010, 2010, 'Genuine Used', 'Right', 'Honda Fit 2010 Right Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNR-UNK-XXX-R-0005', 'WNR', 'Unknown', '', null, null, 'Genuine Used', 'Right', 'Right Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNR-TOY-MAR-R-0006', 'WNR', 'Toyota', 'Mark X', null, null, 'Genuine Used', 'Right', 'Toyota Mark X Right Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNR-TOY-CAL-10-R-0007', 'WNR', 'Toyota', 'Caldina', 2010, 2010, 'Genuine Used', 'Right', 'Toyota Caldina 2010 Right Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNR-TOY-POR-R-0008', 'WNR', 'Toyota', 'Porte', null, null, 'Genuine Used', 'Right', 'Toyota Porte Right Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNR-MZD-CX5-R-0009', 'WNR', 'Mazda', 'CX-5', null, null, 'Genuine Used', 'Right', 'Mazda CX-5 Right Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-HON-FIT-10-L-0010', 'WNL', 'Honda', 'Fit', 2010, 2010, 'Genuine Used', 'Left', 'Honda Fit 2010 Left Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-MAR-L-0011', 'WNL', 'Toyota', 'Mark X', null, null, 'Genuine Used', 'Left', 'Toyota Mark X Left Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNL-HON-CRV-L-0012', 'WNL', 'Honda', 'CR-V RE4', null, null, 'Genuine Used', 'Left', 'Honda CR-V RE4 Left Wing with Bumper Slide & Moulding', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide & Moulding', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-RAU-L-0013', 'WNL', 'Toyota', 'Raum', null, null, 'Genuine Used', 'Left', 'Toyota Raum Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-MZD-CX5-L-0014', 'WNL', 'Mazda', 'CX-5', null, null, 'Genuine Used', 'Left', 'Mazda CX-5 Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-WIS-03-L-0015', 'WNL', 'Toyota', 'Wish', 2003, 2003, 'Genuine Used', 'Left', 'Toyota Wish 2003 Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-WIS-03-L-0016', 'WNL', 'Toyota', 'Wish', 2003, 2003, 'Genuine Used', 'Left', 'Toyota Wish 2003 Left Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-RAC-05-L-0017', 'WNL', 'Toyota', 'Ractis', 2005, 2005, 'Genuine Used', 'Left', 'Toyota Ractis 2005 Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-WIS-10-L-0018', 'WNL', 'Toyota', 'Wish', 2010, 2010, 'Genuine Used', 'Left', 'Toyota Wish 2010 Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-ISI-L-0019', 'WNL', 'Toyota', 'Isis', null, null, 'Genuine Used', 'Left', 'Toyota Isis Left Wing with Indicator', 0, 1, 1, 'Unassigned', 'Wing with Indicator', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-RUM-L-0020', 'WNL', 'Toyota', 'Rumion', null, null, 'Genuine Used', 'Left', 'Toyota Rumion Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-PRE-08-L-0021', 'WNL', 'Toyota', 'Premio', 2008, 2008, 'Genuine Used', 'Left', 'Toyota Premio 2008 Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-NIS-NOT-12-L-0022', 'WNL', 'Nissan', 'Note', 2012, 2012, 'Genuine Used', 'Left', 'Nissan Note 2012 Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-NIS-TEA-10-L-0023', 'WNL', 'Nissan', 'Teana', 2010, 2010, 'Genuine Used', 'Left', 'Nissan Teana 2010 Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-AUR-10-L-0024', 'WNL', 'Toyota', 'Auris', 2010, 2010, 'Genuine Used', 'Left', 'Toyota Auris 2010 Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-VOX-L-0025', 'WNL', 'Toyota', 'Voxy', null, null, 'Genuine Used', 'Left', 'Toyota Voxy Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-PRE-L-0026', 'WNL', 'Toyota', 'Premio 240', null, null, 'Genuine Used', 'Left', 'Toyota Premio 240 Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-WIS-03-L-0027', 'WNL', 'Toyota', 'Wish', 2003, 2003, 'Genuine Used', 'Left', 'Toyota Wish 2003 Left Wing with Indicator', 0, 1, 1, 'Unassigned', 'Wing with Indicator', 'Active', 'Josphat Kamau'),
  ('WNL-SUB-N12-L-0028', 'WNL', 'Subaru', 'N12', null, null, 'Genuine Used', 'Left', 'Subaru N12 Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-NIS-XTR-L-0029', 'WNL', 'Nissan', 'X-Trail NT31', null, null, 'Genuine Used', 'Left', 'Nissan X-Trail NT31 Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-ISI-L-0030', 'WNL', 'Toyota', 'Isis', null, null, 'Genuine Used', 'Left', 'Toyota Isis Left Wing with Indicator', 0, 1, 1, 'Unassigned', 'Wing with Indicator', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-BEL-L-0031', 'WNL', 'Toyota', 'Belta', null, null, 'Genuine Used', 'Left', 'Toyota Belta Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-RAC-10-L-0032', 'WNL', 'Toyota', 'Ractis', 2010, 2010, 'Genuine Used', 'Left', 'Toyota Ractis 2010 Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-CAL-L-0033', 'WNL', 'Toyota', 'Caldina', null, null, 'Genuine Used', 'Left', 'Toyota Caldina Left Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-WIS-03-L-0034', 'WNL', 'Toyota', 'Wish', 2003, 2003, 'Genuine Used', 'Left', 'Toyota Wish 2003 Left Wing with Moulding', 0, 1, 1, 'Unassigned', 'Wing with Moulding', 'Active', 'Josphat Kamau'),
  ('WNR-TOY-PRA-R-0035', 'WNR', 'Toyota', 'Prado 150', null, null, 'Genuine Used', 'Right', 'Toyota Prado 150 Right Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNR-TOY-ISI-R-0036', 'WNR', 'Toyota', 'Isis', null, null, 'Genuine Used', 'Right', 'Toyota Isis Right Wing with Indicator', 0, 1, 1, 'Unassigned', 'Wing with Indicator', 'Active', 'Josphat Kamau'),
  ('WNR-NIS-XTR-R-0037', 'WNR', 'Nissan', 'X-Trail NT31', null, null, 'Genuine Used', 'Right', 'Nissan X-Trail NT31 Right Wing with Bumper Slide & Wing Light', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide & Wing Light', 'Active', 'Josphat Kamau'),
  ('WNR-TOY-PAS-05-R-0038', 'WNR', 'Toyota', 'Passo', 2005, 2005, 'Genuine Used', 'Right', 'Toyota Passo 2005 Right Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNR-NIS-SYL-10-R-0039', 'WNR', 'Nissan', 'Sylphy', 2010, 2010, 'Genuine Used', 'Right', 'Nissan Sylphy 2010 Right Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNR-TOY-PRE-R-0040', 'WNR', 'Toyota', 'Premio 240', null, null, 'Genuine Used', 'Right', 'Toyota Premio 240 Right Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNR-TOY-ISI-R-0041', 'WNR', 'Toyota', 'Isis', null, null, 'Genuine Used', 'Right', 'Toyota Isis Right Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNR-TOY-RUM-R-0042', 'WNR', 'Toyota', 'Rumion', null, null, 'Genuine Used', 'Right', 'Toyota Rumion Right Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNR-HON-CRV-R-0043', 'WNR', 'Honda', 'CR-V RE4', null, null, 'Genuine Used', 'Right', 'Honda CR-V RE4 Right Wing with Bumper Slide & Moulding', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide & Moulding', 'Active', 'Josphat Kamau'),
  ('WNR-NIS-TEA-10-R-0044', 'WNR', 'Nissan', 'Teana', 2010, 2010, 'Genuine Used', 'Right', 'Nissan Teana 2010 Right Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNR-TOY-WIS-03-R-0045', 'WNR', 'Toyota', 'Wish', 2003, 2003, 'Genuine Used', 'Right', 'Toyota Wish 2003 Right Wing with Moulding & Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Moulding & Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNR-NIS-NOT-12-R-0046', 'WNR', 'Nissan', 'Note', 2012, 2012, 'Genuine Used', 'Right', 'Nissan Note 2012 Right Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNL-MIT-PAJ-02-L-0047', 'WNL', 'Mitsubishi', 'Pajero V75', 2002, 2002, 'Genuine Used', 'Left', 'Mitsubishi Pajero V75 2002 Left Wing with Moulding & Wing Mirror', 0, 1, 1, 'Unassigned', 'Wing with Moulding & Wing Mirror', 'Active', 'Josphat Kamau'),
  ('WNL-NIS-JUK-L-0048', 'WNL', 'Nissan', 'Juke', null, null, 'Genuine Used', 'Left', 'Nissan Juke Left Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNL-HON-CRZ-L-0049', 'WNL', 'Honda', 'CR-Z', null, null, 'Genuine Used', 'Left', 'Honda CR-Z Left Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNL-MZD-AXE-13-L-0050', 'WNL', 'Mazda', 'Axela', 2013, 2013, 'Genuine Used', 'Left', 'Mazda Axela 2013 Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-NIS-DUA-L-0051', 'WNL', 'Nissan', 'Dualis', null, null, 'Genuine Used', 'Left', 'Nissan Dualis Left Wing with Bumper Slide & Moulding', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide & Moulding', 'Active', 'Josphat Kamau'),
  ('WNL-TOY-ISI-L-0052', 'WNL', 'Toyota', 'Isis', null, null, 'Genuine Used', 'Left', 'Toyota Isis Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-NIS-SER-L-0053', 'WNL', 'Nissan', 'Serena C26', null, null, 'Genuine Used', 'Left', 'Nissan Serena C26 Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-MIT-RVR-L-0054', 'WNL', 'Mitsubishi', 'RVR', null, null, 'Genuine Used', 'Left', 'Mitsubishi RVR Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-MIT-OUT-12-L-0055', 'WNL', 'Mitsubishi', 'Outlander', 2012, 2012, 'Genuine Used', 'Left', 'Mitsubishi Outlander 2012 Left Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNL-NIS-DUA-L-0056', 'WNL', 'Nissan', 'Dualis', null, null, 'Genuine Used', 'Left', 'Nissan Dualis Left Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNL-SUZ-SX4-L-0057', 'WNL', 'Suzuki', 'SX4', null, null, 'Genuine Used', 'Left', 'Suzuki SX4 Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNL-MZD-AXE-10-L-0058', 'WNL', 'Mazda', 'Axela', 2010, 2010, 'Genuine Used', 'Left', 'Mazda Axela 2010 Left Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNR-SUZ-ESC-R-0059', 'WNR', 'Suzuki', 'Escudo', null, null, 'Genuine Used', 'Right', 'Suzuki Escudo Right Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNR-MZD-AXE-10-R-0060', 'WNR', 'Mazda', 'Axela', 2010, 2010, 'Genuine Used', 'Right', 'Mazda Axela 2010 Right Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNR-HON-CRO-R-0061', 'WNR', 'Honda', 'Crossroad', null, null, 'Genuine Used', 'Right', 'Honda Crossroad Right Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNR-SUB-BP5-R-0062', 'WNR', 'Subaru', 'BP5', null, null, 'Genuine Used', 'Right', 'Subaru BP5 Right Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNR-TOY-PRI-08-R-0063', 'WNR', 'Toyota', 'Prius', 2008, 2008, 'Genuine Used', 'Right', 'Toyota Prius 2008 Right Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNR-TOY-VIT-08-R-0064', 'WNR', 'Toyota', 'Vitz', 2008, 2008, 'Genuine Used', 'Right', 'Toyota Vitz 2008 Right Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('WNR-MIT-OUT-12-R-0065', 'WNR', 'Mitsubishi', 'Outlander', 2012, 2012, 'Genuine Used', 'Right', 'Mitsubishi Outlander 2012 Right Wing with Bumper Slide', 0, 1, 1, 'Unassigned', 'Wing with Bumper Slide', 'Active', 'Josphat Kamau'),
  ('WNR-HON-STR-R-0066', 'WNR', 'Honda', 'Stream', null, null, 'Genuine Used', 'Right', 'Honda Stream Right Standard Wing', 0, 1, 1, 'Unassigned', 'Standard Wing', 'Active', 'Josphat Kamau'),
  ('FBM-NIS-TEA-F-0067', 'FBM', 'Nissan', 'Teana', null, null, 'Genuine Used', 'Front', 'Nissan Teana Front With Fog Lights', 0, 1, 1, 'Unassigned', 'With Fog Lights', 'Active', 'Josphat Kamau'),
  ('FBM-SUB-BR9-F-0068', 'FBM', 'Subaru', 'BR9', null, null, 'Genuine Used', 'Front', 'Subaru BR9 Front With Fog Lights & Grille', 0, 1, 1, 'Unassigned', 'With Fog Lights & Grille', 'Active', 'Josphat Kamau'),
  ('FBM-NIS-SER-F-0069', 'FBM', 'Nissan', 'Serena (New Shape)', null, null, 'Genuine Used', 'Front', 'Nissan Serena (New Shape) Front Standard', 0, 1, 1, 'Unassigned', 'Standard', 'Active', 'Josphat Kamau'),
  ('RBM-TOY-SPA-B-0070', 'RBM', 'Toyota', 'Spade', null, null, 'Genuine Used', 'Rear', 'Toyota Spade Rear Standard', 0, 1, 1, 'Unassigned', 'Standard', 'Active', 'Josphat Kamau'),
  ('FBM-NIS-NOT-F-0071', 'FBM', 'Nissan', 'Note', null, null, 'Genuine Used', 'Front', 'Nissan Note Front With Grille', 0, 1, 1, 'Unassigned', 'With Grille', 'Active', 'Josphat Kamau'),
  ('RBM-HON-FIT-10-B-0072', 'RBM', 'Honda', 'Fit', 2010, 2010, 'Genuine Used', 'Rear', 'Honda Fit 2010 Rear With Reflector', 0, 1, 1, 'Unassigned', 'With Reflector', 'Active', 'Josphat Kamau'),
  ('RBM-HON-FIT-B-0073', 'RBM', 'Honda', 'Fit (New Shape)', null, null, 'Genuine Used', 'Rear', 'Honda Fit (New Shape) Rear Standard', 0, 1, 1, 'Unassigned', 'Standard', 'Active', 'Josphat Kamau'),
  ('RBM-TOY-BBX-B-0074', 'RBM', 'Toyota', 'bB', null, null, 'Genuine Used', 'Rear', 'Toyota bB Rear Standard', 0, 1, 1, 'Unassigned', 'Standard', 'Active', 'Josphat Kamau'),
  ('RBM-MZD-CX5-B-0075', 'RBM', 'Mazda', 'CX-5', null, null, 'Genuine Used', 'Rear', 'Mazda CX-5 Rear With Reflector', 0, 1, 1, 'Unassigned', 'With Reflector', 'Active', 'Josphat Kamau'),
  ('FBM-TOY-PRI-08-F-0076', 'FBM', 'Toyota', 'Prius', 2008, 2008, 'Genuine Used', 'Front', 'Toyota Prius 2008 Front Complete with Fog Lights', 0, 1, 1, 'Unassigned', 'Complete with Fog Lights', 'Active', 'Josphat Kamau'),
  ('FBM-NIS-MAR-10-F-0077', 'FBM', 'Nissan', 'March', 2010, 2010, 'Genuine Used', 'Front', 'Nissan March 2010 Front Complete Assembly', 0, 1, 1, 'Unassigned', 'Complete Assembly', 'Active', 'Josphat Kamau');

-- keep the app's serial generator ahead of these codes:
select setval('public.inventory_serial_seq', 77);
