-- ============================================================
-- BYPASS SHOP — Staff Directory (admin-editable contacts)
-- Run once in: Supabase Dashboard → SQL Editor → New query → Run.
-- Safe to re-run.
--
-- The company phone directory, grouped by department. Instead of names
-- baked into the code, an admin now types each contact in from the app
-- (Settings → Staff Directory). Everyone can see it; only admins edit it.
-- One row = one phone number, so a person with two numbers is two rows.
-- ============================================================

create table if not exists public.staff_contacts (
  id         bigint generated by default as identity primary key,
  dept       text not null default 'General',
  name       text not null,
  role       text,
  phone      text not null,          -- as typed, e.g. "+254 768 553182"
  created_at timestamptz not null default now()
);

create index if not exists staff_contacts_dept_idx on public.staff_contacts (dept);

alter table public.staff_contacts enable row level security;

-- Everyone signed in can read the directory.
drop policy if exists "staff_contacts_read" on public.staff_contacts;
create policy "staff_contacts_read" on public.staff_contacts
  for select to authenticated using (true);

-- Only admins can add / edit / remove entries.
--
-- Through public.is_admin(), not its own copy of the list. This file used to name
-- two addresses by hand and left out management@bypassshop.co, which is_admin()
-- includes — so that admin would have been able to open the directory and then
-- silently fail to save an edit to it. A second copy of an access list is a
-- second chance to disagree with the first.
drop policy if exists "staff_contacts_insert" on public.staff_contacts;
create policy "staff_contacts_insert" on public.staff_contacts
  for insert to authenticated with check (public.is_admin());

drop policy if exists "staff_contacts_update" on public.staff_contacts;
create policy "staff_contacts_update" on public.staff_contacts
  for update to authenticated using (public.is_admin());

drop policy if exists "staff_contacts_delete" on public.staff_contacts;
create policy "staff_contacts_delete" on public.staff_contacts
  for delete to authenticated using (public.is_admin());

-- Keep the directory live across devices.
do $$
begin
  begin execute 'alter publication supabase_realtime add table public.staff_contacts'; exception when others then null; end;
end $$;
